server:
    port: 8080


spring:
    application:
        name: Gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: ProductService
                  uri: http://localhost:8081/
                  predicates:
                      - Path=/product/**

                - id: ReviewService-route
                  uri: lb://ReviewService
                  predicates:
                      - Path=/review/**

                - id: CartService-route
                  uri: lb://CartService
                  predicates:
                      - Path=/cart/**



eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka